---
- name: creating a index.html
  hosts: my
  
  tasks:
    - name: creating a file html file
      file:
        path: /var/www/html/index.html
        state: touch
        
    - name: entering a lines into file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1>Welcome<h1>
