---
- name: Deploy user & group creation
  hosts: my
  
  tasks:
    - name: creating user and group
      user:
        name: deploy-user
        group: deploy
        shell: /bin/bash
 
    - name: installing httpd package
      yum:
        name: httpd
        state: installed

    - name: starting httpd services
      service: 
        name: httpd
        state: started
        enabled: yes

    - name: creating a file html file
      file:
        path: /var/www/html/index.html
        state: touch
        
    - name: entering a lines into file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1>Welcome<h1>
      
    - name: cloning git repo
      git:
        dest: /root/my_repo
        repo: https://github.com/scmgalaxy/ansible-role-template
        clone: yes
          
       
    - name: installing multipackages
      yum: 
        name: "{{ packages }} "
        state: installed
      vars:
        packages:
        - git
        - wget
    - name: cloning git repo
      git:
        dest: /root/my_repo
        repo: https://github.com/scmgalaxy/ansible-role-template
        clone: yes
