---
- name: create a file called “index.html” in /var/www/html with some dummy html contents.
  hosts: web
 
  tasks:
    - name: create a file called “index.html” in /var/www/html
      file:
        path: /var/www/html/index.html
        state: touch

    - name: creating some dummy html contents.
      lineinfile:
        path: /var/www/html/index.html
        line: <h1>Welcome v2<h1>
