- name: install httpd     
  hosts: web
 
  tasks:
    - name: Install httpd on RHEL servers
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
    - name: Install httpd on Ubuntu servers
      apt:
        name: apache2
        state: installed
      when: ansible_os_family == "ubuntu"
