- name: Webserver deployment in two different OS type
  hosts: web

  tasks:
    - name: installing httpd in Redhat servers 
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: install apache in Ubuntu servers
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "ubuntu"

    - name: list the files in /etc directory
      shell: "ls"
      args:
        chdir: "/etc"
      register: with_output
    - debug:
        var: with_output

