---
- name: web server setup
  hosts: web

  vars:
    port: 8080
    myname: Prabu
    age: 38

  tasks:
  - name: Instal httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    with_items:
      - git
      - ntp
      - vim
  - name: start the service
    service:
      name: httpd
      state: started
  - name: Copy the files
    template: src=index.html.j2 dest=/var/wwn.html/index.html
  - name: copy the httpd
    template: src=httpd2.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
    -  Restart httpd

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
  - name: list the directory
      shell: "ls"
      args:
        chdir: "/tmp"
      register:with_output  
  - name: Create group
    group:
      name: deloitte
      state: present

  - name: Create user in deloitte group
    user:
      name: deploy
      group: deloitte


  
    
         
# vars file for webrole
