- name: Cloning https://github.com/scmgalaxy/ansible-role-template
  hosts: web
  environment:
      http_proxy: 'http://web-proxy:8080'
      https_proxy: 'http://web-proxy:8080'
  tasks:
  - name: clone
    git: repo=https://github.com/scmgalaxy/ansible-role-template clone=yes dest=./ansible-role-template
