---
- name: webserver setup
  hosts: web

  vars:
    myname: rubini
    package: "httpd"
    service: "httpd"

  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: Ansible debug example.
    debug:
      msg: "{{ myname }}"
