---
# tasks file for webrole
    - name: install apache
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: install apache in ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "ubuntu"
