---
# tasks file for web

    - name: Install the latest version of Apache
      yum: name={{ item }} state=installed
      when: ansible_os_family == "RedHat"
      with_items:
        - git
        - httpd
        - vim
        - ntp
    - name: Install the latest version of Apache
      apt:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"
    - name: Start service httpd, if not started
      service: name={{ service }} state=started
    - name: Static Content
      template: src=index.html.j2 dest=/var/www/html/index.html
    - name: Copy httpd.conf file
      template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
      notify:
      - Restart httpd 1
  handlers:
    - name: Restart httpd 1
      service:
        name: httpd
        state: restarted
    shell: "find *.txt"
    args:
      chdir: "/tmp"
    register: with_output
  - debug:
      var: with_output
  - debug:
      var: with_output.stdout

