
---
- name: webserver setup
  hosts: web

  vars:
    myname: rajeshk
    package: "httpd"
    service: "httpd"

  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: Copy file with owner and permissions
    copy:
      src: index.html
      dest: /var/www/html/index.html
