---
- name: index.html     
  hosts: web
 
  tasks:
    - name: creating index file 
      file:
        path: /var/www/html/index.html
        state: touch
    - name: adding a line in the file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> index file created by jeeva ! </h1>
