- name: Merging the assignment   
  hosts: web
 
  tasks:
    - name: Creating a group called "deploy"
      group:
        name: deploy
        state: present

    - name: Creating a user called "deploy"
      user:
        name: deploy-user
        group: deploy
        shell: /bin/bash
        state: present

    - name: Installing httpd service
      yum:
        name: httpd
        state: installed

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: creating index file 
      file:
        path: /var/www/html/index.html
        state: touch

    - name: adding a line in the file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> index file created by jeeva ! </h1>
     
    - name: Reboot the ARS
      reboot: 
  
    - name: install get
      yum:
        name: git
        state: installed

    - name: install wget
      yum:
        name: wget
        state: installed

    - name: clone the git repo
      git:
        dest: /home/centos/my_repo
        repo: https://github.com/scmgalaxy/ansible-role-template
        clone: yes
