---
- name: webserver setup
  hosts: web
  vars:
    myname: test_Day3

  tasks:
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RHEL"
    - name: Install the latest version of Apache
      apt:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"
    - name: Ansible debug example.
      debug:
        msg: "{{ myname }}"
