---
- name: webserver setup
  hosts: web

  tasks:
    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Install git
      yum:
        name: git
        state: present
